# Generated by Django 4.2 on 2026-09-30 01:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0004_lab_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', max_length=20)),
                ('min_theory_marks', models.DecimalField(decimal_places=1, default=20.0, max_digits=5)),
                ('min_total_marks', models.DecimalField(decimal_places=1, default=40.0, max_digits=5)),
                ('max_backlogs_for_atkt', models.PositiveSmallIntegerField(default=4)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='academic_structure.department')),
                ('effective_from_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes_starting', to='academic_structure.academicyear')),
                ('effective_to_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schemes_ending', to='academic_structure.academicyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='academic_structure.program')),
            ],
            options={
                'db_table': 'curriculum_schemes',
                'ordering': ['code', 'version'],
            },
        ),
        migrations.CreateModel(
            name='SchemeElectiveGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('group_code', models.CharField(max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('minimum_selection', models.PositiveSmallIntegerField(default=1)),
                ('maximum_selection', models.PositiveSmallIntegerField(default=1)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_groups', to='curriculum.scheme')),
            ],
            options={
                'db_table': 'curriculum_elective_groups',
                'ordering': ['scheme', 'semester_number', 'group_code'],
            },
        ),
        migrations.CreateModel(
            name='SchemeSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('course_code', models.CharField(max_length=30)),
                ('course_level_code', models.CharField(blank=True, default='', max_length=20)),
                ('course_type_code', models.CharField(blank=True, default='', max_length=20)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('total_marks', models.PositiveSmallIntegerField(default=100)),
                ('is_elective', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('elective_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_subjects', to='curriculum.schemeelectivegroup')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_subjects', to='curriculum.scheme')),
            ],
            options={
                'db_table': 'curriculum_scheme_subjects',
                'ordering': ['scheme', 'semester_number', 'display_order', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'curriculum_subjects',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SchemeSubjectAssessmentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('component_type', models.CharField(choices=[('THEORY_FA', 'Theory Formative Assessment'), ('THEORY_SA', 'Theory Summative Assessment'), ('PRACTICAL_FA', 'Practical Formative Assessment'), ('PRACTICAL_SA', 'Practical Summative Assessment'), ('SLA', 'Self Learning Assessment')], max_length=20)),
                ('maximum_marks', models.DecimalField(decimal_places=1, max_digits=6)),
                ('minimum_marks', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('scheme_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='curriculum.schemesubject')),
            ],
            options={
                'db_table': 'curriculum_assessment_components',
                'ordering': ['scheme_subject', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='schemesubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheme_occurrences', to='curriculum.subject'),
        ),
        migrations.CreateModel(
            name='SchemeElectiveOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('elective_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='curriculum.schemeelectivegroup')),
                ('scheme_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elective_options', to='curriculum.schemesubject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elective_options', to='curriculum.subject')),
            ],
            options={
                'db_table': 'curriculum_elective_options',
                'ordering': ['elective_group', 'display_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='schemesubjectassessmentcomponent',
            constraint=models.UniqueConstraint(fields=('scheme_subject', 'component_type'), name='uniq_subject_component'),
        ),
        migrations.AddConstraint(
            model_name='schemesubject',
            constraint=models.UniqueConstraint(fields=('scheme', 'semester_number', 'course_code'), name='uniq_scheme_sem_course'),
        ),
        migrations.AddConstraint(
            model_name='schemeelectivegroup',
            constraint=models.UniqueConstraint(fields=('scheme', 'semester_number', 'group_code'), name='uniq_scheme_sem_elective_group'),
        ),
        migrations.AddConstraint(
            model_name='scheme',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='uniq_scheme_code_version'),
        ),
    ]
