# Generated by Django 4.2 on 2026-09-30 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0004_lab_batch'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Auto-derived from program; informational only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='academic_structure.department'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Null = applies to all programs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='academic_structure.program'),
        ),
    ]
