# Generated by Django 4.2 on 2026-10-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_scheme_department_alter_scheme_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ca_max_marks',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='course_category',
            field=models.CharField(blank=True, choices=[('PCC', 'PCC — Program Core Course'), ('PEC', 'PEC — Program Elective Course'), ('OE', 'OE — Open Elective'), ('MDM', 'MDM — Multidisciplinary Minor'), ('VEC', 'VEC — Value Education Course'), ('PCC_LAB', 'PCC Lab — Program Core Course Laboratory'), ('PROJECT', 'Project / Project Phase'), ('INTERNSHIP', 'Internship'), ('SEMINAR', 'Seminar')], db_index=True, default='', help_text='Empty = legacy subject created before categories existed.', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='ese_max_marks',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='lecture_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Weekly lecture hours (L).', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='mse_max_marks',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_ca_max_marks',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_ese_max_marks',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Weekly practical hours (P).', null=True),
        ),
    ]
