# Generated by Django 5.2.17 on 2026-09-21 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('code', models.CharField(help_text='Academic year code (e.g., 2026-27).', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display title (e.g., Academic Year 2026-2027).', max_length=50)),
                ('start_date', models.DateField(help_text='Academic year commencement date.')),
                ('end_date', models.DateField(help_text='Academic year conclusion date.')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current active academic year for the college.')),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('name', models.CharField(help_text='Full department name.', max_length=150, unique=True)),
                ('code', models.CharField(help_text='Department short code (e.g., CSE, AI_DS, EE, ETC, MAE).', max_length=20, unique=True)),
                ('choice_code', models.CharField(blank=True, default='', help_text='DTE government admission choice code for mapping import rows.', max_length=20)),
                ('seat_capacity', models.PositiveIntegerField(default=60, help_text='Approved annual student intake capacity.')),
                ('start_date', models.DateField(blank=True, help_text='Date when department commenced operations.', null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Department description and profile.')),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('number', models.PositiveSmallIntegerField(help_text='Semester sequence number (1-8).', unique=True)),
                ('name', models.CharField(help_text='Display name (e.g., Semester 1).', max_length=50)),
                ('year_level', models.PositiveSmallIntegerField(help_text='Academic year level: 1 (First Year), 2 (Second Year), 3 (Third Year), 4 (Final Year).')),
                ('term_type', models.CharField(choices=[('ODD', 'Odd Semester'), ('EVEN', 'Even Semester')], help_text='Odd or Even term classification.', max_length=10)),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AcademicContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('term', models.CharField(choices=[('ODD', 'Odd Semester Term'), ('EVEN', 'Even Semester Term'), ('SUMMER', 'Summer Term')], default='ODD', help_text='Active operational term.', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contexts', to='academic_structure.academicyear')),
            ],
            options={
                'db_table': 'academic_contexts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('name', models.CharField(help_text='Full program title (e.g. B.Tech in Computer Science and Engineering).', max_length=150)),
                ('code', models.CharField(help_text='Program code (e.g., BTECH_CSE).', max_length=30)),
                ('degree_type', models.CharField(default='B.Tech', help_text='Degree qualification (B.Tech, M.Tech, Ph.D).', max_length=30)),
                ('duration_years', models.PositiveSmallIntegerField(default=4, help_text='Normal duration in years.')),
                ('total_semesters', models.PositiveSmallIntegerField(default=8, help_text='Total semesters to complete program.')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic_structure.department')),
            ],
            options={
                'db_table': 'programs',
                'ordering': ['department', 'name'],
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('name', models.CharField(help_text='Division identifier (e.g. A, B).', max_length=20)),
                ('seat_capacity', models.PositiveIntegerField(default=60, help_text='Maximum student capacity for this division.')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='academic_structure.academicyear')),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Faculty assigned as Class Teacher for this division.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_divisions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='academic_structure.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='academic_structure.semester')),
            ],
            options={
                'db_table': 'divisions',
                'ordering': ['department', 'semester', 'name'],
                'unique_together': {('department', 'academic_year', 'semester', 'name')},
            },
        ),
    ]
