# Generated by Django 5.2.17 on 2026-09-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccontext',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this academic context is currently active.'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this academic year is active.'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this department is currently active.'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this program is currently active.'),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this semester is active.'),
        ),
    ]
