# Generated by Django 5.2.17 on 2026-09-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0002_academiccontext_is_active_academicyear_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this division is active.'),
        ),
    ]
