# Generated by Django 4.2 on 2026-09-28 04:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0003_division_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('name', models.CharField(help_text='Batch identifier within division (e.g. A1, A2, A3).', max_length=20)),
                ('seat_capacity', models.PositiveIntegerField(default=20, help_text='Maximum student capacity for this lab batch.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this lab batch is active.')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_batches', to='academic_structure.division')),
            ],
            options={
                'db_table': 'lab_batches',
                'ordering': ['division', 'name'],
                'unique_together': {('division', 'name')},
            },
        ),
    ]
