# Generated by Django 4.2 on 2026-09-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0004_lab_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='alternate_choice_codes',
            field=models.JSONField(blank=True, default=list, help_text='Alternate choice codes for the same department (e.g. DSE/TFWS-style codes like 0603624211T).'),
        ),
    ]
