# Generated by Django 4.2 on 2026-10-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0006_fix_department_choice_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='university_program_code',
            field=models.CharField(blank=True, db_index=True, help_text='University-issued program code for admission imports (e.g. 11242 for CSE). Data-driven; never hard-coded in import logic.', max_length=20, null=True, unique=True),
        ),
    ]
