# Generated by Django 5.2.17 on 2026-09-21 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('actor_username', models.CharField(blank=True, default='', help_text='Username snapshot at time of action (preserved even if user deleted).', max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', help_text='Role the actor was operating under at time of action.', max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('ROLE_ASSIGN', 'Role Assignment'), ('ROLE_REVOKE', 'Role Revocation'), ('SENSITIVE_REVEAL', 'Sensitive Data Reveal'), ('IMPORT', 'Data Import'), ('EXPORT', 'Data Export'), ('VERIFY', 'Verification'), ('PAYMENT', 'Payment'), ('STATUS_CHANGE', 'Status Change')], db_index=True, help_text='Type of action performed.', max_length=30)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of the action.')),
                ('target_type', models.CharField(db_index=True, help_text='Type of the target entity (e.g., Student, User, Payment).', max_length=100)),
                ('target_id', models.CharField(blank=True, db_index=True, default='', help_text='ID of the target entity.', max_length=255)),
                ('target_display', models.CharField(blank=True, default='', help_text='Human-readable label for the target (e.g., student name).', max_length=255)),
                ('old_value', models.JSONField(blank=True, help_text='Previous state (JSON). Null for create/login actions.', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New state (JSON). Null for delete/logout actions.', null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for the action, if applicable.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser/client user-agent string.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Exact time the action was recorded.')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
