# Generated by Django 5.2.17 on 2026-09-21 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0003_division_is_active'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category_quota', models.CharField(choices=[('ALL', 'All Categories'), ('OPEN', 'Open Category'), ('OBC_EBC', 'OBC / EBC Category (50% Concession)'), ('SC_ST', 'SC / ST Category (100% Tuition Waiver)'), ('TFWS', 'Tuition Fee Waiver Scheme (TFWS)'), ('EWS', 'Economically Weaker Section (EWS)')], default='ALL', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_refundable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_heads', to='academic_structure.academicyear')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_heads', to='academic_structure.program')),
            ],
            options={
                'db_table': 'finance_fee_heads',
                'ordering': ['academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('receipt_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_fee_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('ONLINE', 'Online Gateway (UPI/Netbanking)'), ('DD', 'Demand Draft'), ('CHALLAN', 'Bank Challan'), ('CASH', 'Cash Counter'), ('NEFT', 'NEFT / RTGS Transfer')], default='ONLINE', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('PENDING', 'Pending Payment'), ('REFUNDED', 'Refunded')], db_index=True, default='PAID', max_length=20)),
                ('payment_date', models.DateField()),
                ('remarks', models.TextField(blank=True, default='')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='academic_structure.academicyear')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='students.student')),
            ],
            options={
                'db_table': 'finance_payment_ledgers',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
