# Generated by Django 5.2.17 on 2026-09-27 18:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feehead',
            options={'ordering': ['display_order', 'academic_year', 'name']},
        ),
        migrations.AddField(
            model_name='feehead',
            name='allowed_amounts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feehead',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feehead',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feehead',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='feehead',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
