# Generated by Django 5.2.17 on 2026-09-27 19:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0003_division_is_active'),
        ('finance', '0002_alter_feehead_options_feehead_allowed_amounts_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('fee_breakdown', models.JSONField(blank=True, default=dict, help_text='Mapping of fee head names to assessed amounts.')),
                ('total_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_marked', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_assessments', to='academic_structure.academicyear')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_fees', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assessments', to='students.student')),
            ],
            options={
                'db_table': 'finance_student_fee_assessments',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
