# Generated by Django 5.2.17 on 2026-09-28 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0004_lab_batch'),
        ('finance', '0003_studentfeeassessment'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentledger',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='uniq_payment_student_year'),
        ),
    ]
