# Generated by Django 4.2 on 2026-10-06 18:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentenrollment_idx_enr_current_dept_div'),
        ('academic_structure', '0008_seed_university_program_codes'),
        ('finance', '0004_unique_student_year_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayRawEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('event_source', models.CharField(default='EASEBUZZ', max_length=50)),
                ('event_type', models.CharField(default='CALLBACK', max_length=50)),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'finance_gateway_raw_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentfeeassessment',
            name='allow_online_payment',
            field=models.BooleanField(db_index=True, default=False, help_text='Accountant selection to allow candidate to pay online via payment gateway.'),
        ),
        migrations.CreateModel(
            name='OnlinePaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique college transaction reference sent to Easebuzz (txnid).', max_length=64, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Client or server idempotency key to prevent double initiation.', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Exact payable fee derived authoritatively from StudentFeeAssessment.', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('REDIRECTED', 'Redirected to Gateway'), ('PENDING', 'Pending Verification'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled by User'), ('EXPIRED', 'Payment Link Expired'), ('UNKNOWN', 'Ambiguous / Needs Re-check')], db_index=True, default='INITIATED', max_length=20)),
                ('gateway_provider', models.CharField(default='EASEBUZZ', max_length=30)),
                ('easebuzz_txn_id', models.CharField(blank=True, db_index=True, default='', help_text='Easebuzz internal transaction reference (easepayid).', max_length=100)),
                ('easebuzz_status', models.CharField(blank=True, default='', max_length=50)),
                ('payment_mode', models.CharField(blank=True, default='', help_text='Payment instrument (e.g. UPI, NetBanking, Credit Card, Debit Card).', max_length=50)),
                ('checkout_url', models.TextField(blank=True, default='')),
                ('access_key', models.CharField(blank=True, default='', max_length=150)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('raw_initiation_response', models.JSONField(blank=True, default=dict)),
                ('raw_callback_payload', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payment_attempts', to='academic_structure.academicyear')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payment_attempts', to='finance.studentfeeassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payment_attempts', to='students.student')),
            ],
            options={
                'db_table': 'finance_online_payment_attempts',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeReceiptCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_counter', to='academic_structure.academicyear')),
            ],
            options={
                'db_table': 'finance_fee_receipt_counters',
            },
        ),
        migrations.AddConstraint(
            model_name='onlinepaymentattempt',
            constraint=models.UniqueConstraint(fields=('student', 'idempotency_key'), name='uniq_online_payment_student_idempotency'),
        ),
    ]
