# Generated by Django 4.2 on 2026-10-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_gatewayrawevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepaymentattempt',
            name='customer_email',
            field=models.CharField(blank=True, default='', help_text='Email sent to Easebuzz at initiation; reused for verify/retrieve hash.', max_length=254),
        ),
        migrations.AddField(
            model_name='onlinepaymentattempt',
            name='customer_phone',
            field=models.CharField(blank=True, default='', help_text='Phone sent to Easebuzz at initiation; reused for verify/retrieve hash.', max_length=15),
        ),
    ]
