# Generated by Django 4.2 on 2026-10-09 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_scholarship'),
        ('finance', '0006_onlinepaymentattempt_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeeassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_assessments', to='students.student'),
        ),
    ]
