# Generated by Django 5.2.17 on 2026-09-21 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('codename', models.CharField(help_text='Unique permission code (e.g., student.view, student.edit).', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission description.', max_length=200)),
                ('module', models.CharField(db_index=True, help_text='Module/domain this permission belongs to (e.g., student, faculty, finance).', max_length=50)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['module', 'codename'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('codename', models.CharField(help_text='Unique role code (e.g., STUDENT, FACULTY, HOD).', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable role name.', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text="Description of this role's purpose and responsibilities.")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is currently active.')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Unique login identifier.', max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional for students).', max_length=254, null=True)),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('SYSADMIN', 'System Administrator')], help_text='Account classification: STUDENT, FACULTY, or SYSADMIN. This is for routing/display only — NOT for authorization.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user account is active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether user can access Django admin (Sysadmin only).')),
                ('must_change_password', models.BooleanField(default=True, help_text='If True, user must change password on next login.')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Consecutive failed login attempts.')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account locked until this time after too many failed attempts.', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('password_hash', models.CharField(help_text='Hashed previous password.', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('department_id', models.UUIDField(blank=True, help_text='Department scope for HOD, CLASS_TEACHER roles. FK managed at application level.', null=True)),
                ('division_id', models.UUIDField(blank=True, help_text='Division scope for CLASS_TEACHER role. FK managed at application level.', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this role assignment expires (null = no expiry).', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=20)),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for assignment/revocation.')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who made this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_revoked', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='authentication.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='role_assign_user_id_541f3f_idx'), models.Index(fields=['role', 'status'], name='role_assign_role_id_a0eb10_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.role')),
            ],
            options={
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
