# Generated by Django 5.2.17 on 2026-09-21 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0003_division_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('enrollment_no', models.CharField(blank=True, db_index=True, help_text='University enrollment number (e.g. DBATU PRN).', max_length=50, null=True, unique=True)),
                ('application_id', models.CharField(blank=True, db_index=True, help_text='Government DTE admission application ID (e.g., EN26123456).', max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Full formatted name.', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Enrolled'), ('PASSED_OUT', 'Graduated / Passed Out'), ('DETAINED', 'Year Down / Detained'), ('CANCELLED', 'Admission Cancelled'), ('TRANSFERRED', 'Transferred to Other College')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, help_text='Linked user login account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAadhaarDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='aadhaar_details', serialize=False, to='students.student')),
                ('aadhaar_number_encrypted', models.CharField(help_text='Encrypted Aadhaar number.', max_length=255)),
                ('aadhaar_number_masked', models.CharField(help_text='Masked representation (e.g. XXXX-XXXX-1234).', max_length=20)),
                ('enrolment_id', models.CharField(blank=True, default='', max_length=50)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student_aadhaar_details',
            },
        ),
        migrations.CreateModel(
            name='StudentPersonalDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal_details', serialize=False, to='students.student')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('place_of_birth', models.CharField(blank=True, default='', max_length=100)),
                ('religion', models.CharField(blank=True, default='', max_length=50)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('mother_tongue', models.CharField(blank=True, default='', max_length=50)),
                ('domicile_state', models.CharField(default='Maharashtra', max_length=50)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_mobile', models.CharField(blank=True, default='', max_length=15)),
                ('blood_group', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'db_table': 'student_personal_details',
            },
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('address_type', models.CharField(choices=[('PERMANENT', 'Permanent Address'), ('CORRESPONDENCE', 'Correspondence Address')], default='PERMANENT', max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_3', models.CharField(blank=True, default='', max_length=255)),
                ('village', models.CharField(blank=True, default='', max_length=100)),
                ('taluka', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('is_current', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='students.student')),
            ],
            options={
                'db_table': 'student_addresses',
                'ordering': ['student', 'address_type'],
            },
        ),
        migrations.CreateModel(
            name='StudentBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('account_holder_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(blank=True, default='', max_length=150)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_number_encrypted', models.CharField(max_length=255)),
                ('account_number_masked', models.CharField(max_length=30)),
                ('is_primary', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='students.student')),
            ],
            options={
                'db_table': 'student_bank_accounts',
                'ordering': ['student', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('document_type', models.CharField(choices=[('PHOTO', 'Passport Photograph'), ('SIGNATURE', 'Student Signature'), ('AADHAAR', 'Aadhaar Card'), ('ALLOTMENT_LETTER', 'CAP Allotment Letter'), ('SSC_MARKSHEET', '10th / SSC Marksheet'), ('HSC_MARKSHEET', '12th / HSC Marksheet'), ('DIPLOMA_MARKSHEET', 'Diploma Marksheet'), ('CASTE_CERTIFICATE', 'Caste Certificate'), ('INCOME_CERTIFICATE', 'Income Certificate'), ('OTHER', 'Other Supporting Document')], db_index=True, default='OTHER', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('file_path', models.CharField(help_text='Secure storage file reference.', max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes.')),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA-256 hash.', max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
            options={
                'db_table': 'student_documents',
                'ordering': ['student', 'document_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Guardian')], default='FATHER', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student')),
            ],
            options={
                'db_table': 'student_guardians',
                'ordering': ['student', 'relationship'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('roll_number', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Currently Enrolled'), ('COMPLETED', 'Semester Term Completed'), ('PROMOTED', 'Promoted to Next Semester'), ('DETAINED', 'Detained / Not Promoted'), ('BACKLOG', 'Has Backlogs'), ('DROPOUT', 'Discontinued')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the student active operational enrollment record.')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academic_structure.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academic_structure.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='academic_structure.division')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academic_structure.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academic_structure.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'db_table': 'student_enrollments',
                'ordering': ['-academic_year__start_date', '-semester__number'],
                'unique_together': {('student', 'academic_year', 'semester')},
            },
        ),
    ]
