# Generated by Django 4.2 on 2026-09-29 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0004_lab_batch'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_direct_second_year',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether student was admitted via Direct Second Year (Lateral Entry).'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='lab_batch',
            field=models.ForeignKey(blank=True, help_text='Assigned laboratory / practical batch (e.g., A1, A2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='academic_structure.labbatch'),
        ),
    ]
