# Generated by Django 4.2 on 2026-09-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('students', '0002_student_is_direct_second_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='scheme',
            field=models.ForeignKey(blank=True, help_text='Curriculum scheme the student entered under; preserved on promotion.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='curriculum.scheme'),
        ),
    ]
