# Generated by Django 4.2 on 2026-10-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0006_fix_department_choice_codes'),
        ('students', '0003_studentenrollment_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='FY (First Year) or DSE (Direct Second Year lateral entry).', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.ForeignKey(blank=True, help_text='Academic year the student was admitted in (formula anchor).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admitted_students', to='academic_structure.academicyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='repeat_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Times the student repeated a year (detention); placement itself lives on enrollments.'),
        ),
    ]
