# Generated by Django 4.2 on 2026-10-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_admission_type_student_admission_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='placement_confirmed',
            field=models.BooleanField(db_index=True, default=False, help_text='HOD confirmed the sem/division placement (formula suggestion accepted or corrected).'),
        ),
    ]
