# Generated by Django 4.2 on 2026-10-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_backfill_admission_anchor'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['is_current', 'department', 'division'], name='idx_enr_current_dept_div'),
        ),
    ]
