# Generated by Django 4.2 on 2026-10-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentenrollment_idx_enr_current_dept_div'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('student',), name='uniq_current_enrollment_per_student'),
        ),
    ]
