# Generated by Django 4.2 on 2026-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_current_enrollment_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonaldetail',
            name='abc_id',
            field=models.CharField(blank=True, default='', help_text='Academic Bank of Credits ID.', max_length=50),
        ),
        migrations.AddField(
            model_name='studentpersonaldetail',
            name='caste',
            field=models.CharField(blank=True, default='', help_text='Sub-caste e.g. Maratha, Kunbi, Sutar.', max_length=100),
        ),
        migrations.AddField(
            model_name='studentpersonaldetail',
            name='marital_status',
            field=models.CharField(blank=True, default='Unmarried', max_length=20),
        ),
    ]
