# Generated by Django 5.2.17 on 2026-09-21 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0003_division_is_active'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('file_name', models.CharField(max_length=255)),
                ('file_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('UPLOADED', 'File Uploaded'), ('VALIDATING', 'Validating Rows'), ('VALIDATED', 'Validation Complete'), ('IMPORTING', 'Importing Into Core Records'), ('COMPLETED', 'Successfully Completed'), ('FAILED', 'Failed with Errors')], db_index=True, default='UPLOADED', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary_report', models.JSONField(blank=True, default=dict)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='academic_structure.academicyear')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_admission_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admission_import_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('row_number', models.PositiveIntegerField()),
                ('application_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=255)),
                ('allotted_course', models.CharField(blank=True, default='', max_length=255)),
                ('raw_data', models.JSONField(default=dict, help_text='Complete dictionary of raw 59 columns extracted from source sheet.')),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('DUPLICATE', 'Duplicate / Already Exists'), ('IMPORTED', 'Imported into Student Records'), ('FAILED', 'Import Failed')], db_index=True, default='PENDING', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='admissions.importbatch')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_import_rows', to='students.student')),
            ],
            options={
                'db_table': 'admission_import_rows',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('application_id', models.CharField(db_index=True, max_length=50)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admission_type', models.CharField(default='CAP', max_length=50)),
                ('candidature_type', models.CharField(blank=True, default='', max_length=50)),
                ('institute_code', models.CharField(default='6270', max_length=20)),
                ('institute_name', models.CharField(default='Government College of Engineering, Kolhapur', max_length=255)),
                ('choice_code', models.CharField(blank=True, default='', max_length=50)),
                ('seat_type', models.CharField(blank=True, default='', max_length=50)),
                ('allotted_seat_type', models.CharField(blank=True, default='', max_length=50)),
                ('merit_no', models.PositiveIntegerField(blank=True, null=True)),
                ('merit_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entrance_exam_type', models.CharField(blank=True, default='MHT-CET', max_length=50)),
                ('entrance_percentile', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_admissions', to='academic_structure.academicyear')),
                ('source_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admissions', to='admissions.importrow')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='students.student')),
            ],
            options={
                'db_table': 'student_admissions',
                'ordering': ['-academic_year__start_date', 'merit_no'],
            },
        ),
    ]
