# Generated by Django 5.2.17 on 2026-09-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='conflict_rows',
            field=models.PositiveIntegerField(default=0, help_text='Rows needing manual review (conflicting identity matches).'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='failed_rows',
            field=models.PositiveIntegerField(default=0, help_text='Rows that failed during final import.'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='Original file size in bytes.'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source_file',
            field=models.FileField(blank=True, help_text='Preserved original uploaded file for proof/audit.', null=True, upload_to='admission_imports/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='choice_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Government choice code driving department/program mapping.', max_length=50),
        ),
        migrations.AddField(
            model_name='importrow',
            name='enrollment_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Enrollment No from source file when provided.', max_length=50),
        ),
        migrations.AddField(
            model_name='importrow',
            name='import_error',
            field=models.TextField(blank=True, default='', help_text='Per-row failure reason when final import fails (retryable).'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='matching_detail',
            field=models.JSONField(blank=True, default=dict, help_text='Matched student reference / conflict explanation for manual review.'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='matching_status',
            field=models.CharField(choices=[('PENDING', 'Pending Matching'), ('NO_MATCH', 'No Existing Match (New Student)'), ('MATCHED', 'Matched Single Existing Student'), ('CONFLICT', 'Conflicting Matches — Manual Review')], db_index=True, default='PENDING', help_text='Identity-matching outcome per precedence rules.', max_length=20),
        ),
        migrations.AddField(
            model_name='importrow',
            name='normalized_data',
            field=models.JSONField(blank=True, default=dict, help_text='Cleaned/normalized values derived from raw_data (trimmed names, dates, mobiles).'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'File Uploaded'), ('VALIDATING', 'Validating Rows'), ('VALIDATED', 'Validation Complete'), ('IMPORTING', 'Importing Into Core Records'), ('COMPLETED', 'Successfully Completed'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('FAILED', 'Failed with Errors')], db_index=True, default='UPLOADED', max_length=20),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='raw_data',
            field=models.JSONField(default=dict, help_text='Complete dictionary of raw columns extracted from source sheet (immutable).'),
        ),
        migrations.AlterField(
            model_name='importrow',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Validation'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('DUPLICATE', 'Duplicate / Already Exists'), ('CONFLICT', 'Conflict — Needs Manual Review'), ('IMPORTED', 'Imported into Student Records'), ('FAILED', 'Import Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'validation_status'], name='admission_i_batch_i_262092_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'matching_status'], name='admission_i_batch_i_51ea58_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='uniq_import_row_batch_number'),
        ),
    ]
