# Generated by Django 4.2 on 2026-09-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_importbatch_conflict_rows_importbatch_failed_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='admission_type',
            field=models.CharField(choices=[('FIRST_YEAR', 'First Year (Regular Entry)'), ('DIRECT_SECOND_YEAR', 'Direct Second Year (Lateral Entry)')], db_index=True, default='FIRST_YEAR', help_text='Stream classification: First Year or Direct Second Year.', max_length=30),
        ),
    ]
