# Generated by Django 4.2 on 2026-09-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_importbatch_admission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Government admission category (OPEN/OBC/SC/ST/VJ/NT-B/NT-C/NT-D/SBC/SEBC/EWS/TFWS/PWD/DEF/ORPHAN).', max_length=20),
        ),
    ]
