# Generated by Django 4.2 on 2026-10-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_studentadmission_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='program_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='University-issued program code driving department/program mapping when choice code is absent.', max_length=50),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='program_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
