# Generated by Django 4.2 on 2026-10-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_importrow_program_code_studentadmission_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='admission_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='entrance_exam_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='institute_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='institute_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
