# Generated by Django 5.2.17 on 2026-09-21 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0003_division_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('employee_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('ASSISTANT_PROFESSOR', 'Assistant Professor'), ('ADJUNCT_PROFESSOR', 'Adjunct Professor'), ('LECTURER', 'Lecturer'), ('HOD', 'Head of Department'), ('PRINCIPAL', 'Principal')], default='ASSISTANT_PROFESSOR', max_length=50)),
                ('employment_type', models.CharField(choices=[('REGULAR', 'Regular / Permanent'), ('CONTRACT', 'Contractual'), ('AD_HOC', 'Ad-hoc'), ('VISITING', 'Visiting Faculty')], default='REGULAR', max_length=20)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RELIEVED', 'Relieved / Resigned'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('date_of_joining', models.DateField()),
                ('date_of_relieving', models.DateField(blank=True, null=True)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=15)),
                ('residential_telephone', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_members', to='academic_structure.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculties',
                'ordering': ['department', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyPersonalDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal_details', serialize=False, to='faculty.faculty')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('domicile_state', models.CharField(default='Maharashtra', max_length=50)),
                ('constitutional_category', models.CharField(blank=True, default='', max_length=50)),
                ('blood_group', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'db_table': 'faculty_personal_details',
            },
        ),
        migrations.CreateModel(
            name='FacultyAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('address_type', models.CharField(choices=[('PERMANENT', 'Permanent Address'), ('CORRESPONDENCE', 'Correspondence Address')], default='PERMANENT', max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('district', models.CharField(default='Kolhapur', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('is_current', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='faculty.faculty')),
            ],
            options={
                'db_table': 'faculty_addresses',
                'ordering': ['faculty', 'address_type'],
            },
        ),
        migrations.CreateModel(
            name='FacultyBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('account_holder_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(blank=True, default='', max_length=150)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_number_encrypted', models.CharField(max_length=255)),
                ('account_number_masked', models.CharField(max_length=30)),
                ('is_primary', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='faculty.faculty')),
            ],
            options={
                'db_table': 'faculty_bank_accounts',
                'ordering': ['faculty', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='FacultyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('document_type', models.CharField(choices=[('PHOTO', 'Photograph'), ('SIGNATURE', 'Signature'), ('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('APPOINTMENT_LETTER', 'Appointment Order'), ('DEGREE_CERTIFICATE', 'Degree Certificate'), ('RESUME', 'Curriculum Vitae (AICTE Format)'), ('OTHER', 'Other Document')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='faculty.faculty')),
            ],
            options={
                'db_table': 'faculty_documents',
                'ordering': ['faculty', 'document_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='FacultyExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('experience_type', models.CharField(choices=[('TEACHING', 'Teaching Experience'), ('INDUSTRY', 'Industry Experience'), ('RESEARCH', 'Research Experience')], default='TEACHING', max_length=20)),
                ('organization', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('remarks', models.TextField(blank=True, default='')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='faculty.faculty')),
            ],
            options={
                'db_table': 'faculty_experiences',
                'ordering': ['faculty', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FacultyGuidance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('guidance_type', models.CharField(choices=[('PHD', 'Ph.D. Thesis Guidance'), ('MASTERS_PROJECT', "Master's Dissertation"), ('UG_PROJECT', 'B.Tech Capstone Project')], max_length=20)),
                ('candidate_name', models.CharField(max_length=150)),
                ('project_title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed / Awarded')], default='ONGOING', max_length=20)),
                ('completion_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_records', to='faculty.faculty')),
            ],
            options={
                'db_table': 'faculty_guidance',
                'ordering': ['faculty', '-status'],
            },
        ),
        migrations.CreateModel(
            name='FacultyPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('title', models.CharField(max_length=350)),
                ('journal_or_conference', models.CharField(max_length=300)),
                ('publication_type', models.CharField(choices=[('JOURNAL', 'Journal Article'), ('CONFERENCE', 'Conference Proceeding'), ('BOOK', 'Book / Book Chapter'), ('PATENT', 'Patent')], default='JOURNAL', max_length=20)),
                ('scope', models.CharField(choices=[('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], default='INTERNATIONAL', max_length=20)),
                ('publication_year', models.PositiveSmallIntegerField()),
                ('doi_or_issn', models.CharField(blank=True, default='', max_length=100)),
                ('indexing', models.CharField(blank=True, default='Scopus / Web of Science', max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='faculty.faculty')),
            ],
            options={
                'db_table': 'faculty_publications',
                'ordering': ['faculty', '-publication_year'],
            },
        ),
        migrations.CreateModel(
            name='FacultyQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('qualification_level', models.CharField(choices=[('UG', 'Undergraduate (B.E./B.Tech)'), ('PG', 'Postgraduate (M.E./M.Tech)'), ('PHD', 'Doctorate (Ph.D.)'), ('POSTDOC', 'Post-Doctoral'), ('OTHER', 'Other Certification')], max_length=20)),
                ('degree_name', models.CharField(help_text='e.g. B.E. Computer Science', max_length=100)),
                ('specialization', models.CharField(blank=True, default='', max_length=150)),
                ('institution_university', models.CharField(max_length=255)),
                ('passing_year', models.PositiveSmallIntegerField()),
                ('percentage_or_cgpa', models.CharField(blank=True, default='', max_length=20)),
                ('class_or_grade', models.CharField(blank=True, default='First Class', max_length=50)),
                ('is_highest', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='faculty.faculty')),
            ],
            options={
                'db_table': 'faculty_qualifications',
                'ordering': ['faculty', '-passing_year'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID primary key.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp.')),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('PRIMARY_FACULTY', 'Primary Course Instructor'), ('CO_FACULTY', 'Co-Instructor'), ('LAB_INSTRUCTOR', 'Lab Practical Incharge')], default='PRIMARY_FACULTY', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='academic_structure.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='academic_structure.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_assignments', to='academic_structure.division')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='faculty.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='academic_structure.semester')),
            ],
            options={
                'db_table': 'faculty_teaching_assignments',
                'ordering': ['-academic_year__start_date', 'semester__number', 'subject_code'],
            },
        ),
    ]
