# Generated by Django 4.2 on 2026-10-02 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_scheme_department_alter_scheme_program'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='scheme_subject',
            field=models.ForeignKey(blank=True, help_text='Scheme-defined subject slot; fills name/code automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_assignments', to='curriculum.schemesubject'),
        ),
    ]
