# Generated by Django 4.2 on 2026-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_teachingassignment_scheme_subject'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('division', 'subject_code', 'role'), name='uniq_active_slot_teacher'),
        ),
    ]
